name: hive_eg
description: Short and simple Flutter Hike package explaination.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter:
    # git:
    #   url: https://github.com/jinosh05/hive_flutter
  path_provider: ^2.0.15
  # platform: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.4
  analyzer: ^5.13.0
  file: ^7.0.0
  pub_semver: ^2.1.4

dependency_overrides:
  file: ^6.1.4

flutter:
  uses-material-design: true
